language: node_js
node_js:
- 10.1.0
cache:
  yarn: true
script:
- docker-compose up -
- while ! $(curl --silent --fail --output /dev/null http://localhost:8080/); do sleep 1; done
- ./fixture/purge.sh
- ./fixture/import.sh
- yarn install
- yarn gatsby build
- touch public/.nojekyll
